name: Minium Support Rust Version Test

concurrency:
  group: msrv-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
   types: [opened, synchronize, reopened]
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  build_on_msrv:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install Rust 1.88
      run: rustup install 1.88

    - name: Build test
      run: cargo +1.88 build --ignore-rust-version
